---
name: Bump Pre-commit

on:
  schedule:
    # Every day at 7 AM JST
    - cron: "0 22 * * *"
  workflow_dispatch:
    inputs:
      regex:
        description: "Repo names regex:"
        required: true
        default: "^(.+jolie.+)$"
        type: string

permissions: write-all

defaults:
  run:
    shell: sh

env:
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"
  REGEX_DEFAULT: "^(.*)$"

jobs:
  bump-pre-commit:
    name: Bump pre-commit
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Install mtoohey31/gh-foreach
        run: gh extension install mtoohey31/gh-foreach

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run script
        env:
          INPUT_REGEX: "${{ inputs.regex || env.REGEX_DEFAULT }}"
        run: |
          gh foreach run \
            --cleanup \
            --no-confirm \
            --shell sh \
            --visibility public \
            --affiliations owner \
            --regex "${INPUT_REGEX}" \
            ./bump-pre-commit.sh
        working-directory: ${{ github.workspace }}/src
