---
name: Bump Pre-commit

on:
  schedule:
    # Every day at 7 AM JST
    - cron: "0 22 * * *"
  workflow_dispatch:
    inputs:
      regex:
        description: "Repo names regex:"
        required: true
        default: "^(.*)$"
        type: string

defaults:
  run:
    shell: sh

env:
  REGEX_DEFAULT: "^(.*)$"

jobs:
  bump-pre-commit:
    name: Bump pre-commit
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Create GitHub token
        uses: actions/create-github-app-token@v1
        id: gh-app-bump-pre-commit
        with:
          app-id: ${{ vars.GH_APP_ID_BUMP_PRE_COMMIT }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY_BUMP_PRE_COMMIT }}
          owner: ${{ github.repository_owner }}

      - name: Install mtoohey31/gh-foreach
        env:
          GH_TOKEN: "${{ steps.gh-app-bump-pre-commit.outputs.token }}"
        run: gh extension install mtoohey31/gh-foreach

      - name: Run script
        env:
          GH_TOKEN: "${{ steps.gh-app-bump-pre-commit.outputs.token }}"
          INPUT_REGEX: "${{ inputs.regex || env.REGEX_DEFAULT }}"
        run: |
          gh foreach run \
            --cleanup \
            --no-confirm \
            --visibility public \
            --affiliations owner \
            --regex "${INPUT_REGEX}" \
            ./bump-pre-commit.sh \
            "${GH_TOKEN}"
        working-directory: ${{ github.workspace }}/src
